### ISSUE TITLE
QC dans Fill in metadata

### ISSUE THREAD

**Issue by Elineau** [picheral/Zooprocess#10]
Les champs de QC (sur le depth, le volume filtré, la qualité du flacon, etc...) sont des listes déroulantes avec code numéros 0, 1, 2, 3

En sortie (fichier meta.txt, pid, table ecotaxa.tsv) seuls les numéros 0,1 2, et 3 apparaissent dans les colonnes des QC sans comprendre ce que cela signifie...

**Comment by picheral** [comment]
Ne peut guère être documenté dans les fichiers TSV... A mettre dans les manuels d'utilisation des données Zooscan sur le site de la PIQv.
