### ISSUE TITLE
Zooscan : champ motoda fraction 

### ISSUE THREAD

**Issue by Elineau** [picheral/Zooprocess#11]
A l'étape du scan sample sur zooprocess, l'opérateur doit remplir, entre autre, un champ sur la fraction motoda utilisée.
Ce champ doit être rendu obligatoire. Si champ reste à 9999 ou vide le scan du sample est rendu impossible.

**Comment by picheral** [comment]
Tester :
- Si Motoda : puissance de 2
- Ne pas autoriser les valeurs qui commencent par 9999.

**Comment by picheral** [comment]
Fixed in 7.40
