### ISSUE TITLE
zooprocess : flowcam et meta

### ISSUE THREAD

**Issue by Elineau** [picheral/Zooprocess#4]
pour le fill in metadata, il manque
- maille du filet
- barcode
- tamis utilisés
- liste déroulante (vivant, lugolé, formolé, alcool)
il faudrait comme pour le zooscan avoir 2 fenêtres différentes : 1 concernant les data de prélèvements et 1 concernant les data d'analyses avec donc 2 tables .csv dans le répertoire meta

**Comment by picheral** [comment]
version 8.15
