### ISSUE TITLE
zooprocess : UVP5 + process DAT and BRU files

### ISSUE THREAD

**Issue by Elineau** [picheral/Zooprocess#6]
Une fois avoir cliquer sur l'outil Process DAT, BRU, PID and vignettes ; l'outil Plot profiles ? est cliquable alors que ça ne fonctionne pas si il n y a pas eu de process avant !

rendre ces options plus explicites : 

- Process DAT, BRU, PID ans vignettes only
- Process DAT, BRU, PID ans vignettes + PLOT profiles

**Comment by picheral** [comment]
Il faut clarifier. Si le PLOT Profile est validé dans le menu du Process DAT, BRU et vignettes, il sera effectué dans la foulée. Il y aura par contre des problèmes (peut-être) si on y accède directement à partir du menu principal.

**Comment by picheral** [comment]
Le plot des profiles est systématique. Option supprimée en version 7.44
