### ISSUE TITLE
Metadata sur l'intérieur du flacon

### ISSUE THREAD

**Issue by Elineau** [picheral/Zooprocess#9]
1. Le champ sample quality où on doit commenter la présence d'élèments perturbateurs dans le flacon (phyto soupe, grosse méduse, etc....) apparaît dans la fenêtre des metadata à l'étape du Fill in metadata.
Nous pouvons répondre à ce champ uniquement que nous avons ouverts l'échantillon donc au moment du scan (à mettre dans la table scan_header)

2. Il faudrait ajouter dans cette liste déroulante : présence de cristaux de borax (situation qui arrive malheureusement assez souvent)

**Comment by picheral** [comment]
Le sample doit être observé au moment où on saisit les metadata. Cela correspond d'ailleurs au moment ou on y place le barcode et on regarde sa qualité. Déplacer ce champs aurait d'autre part un fort impact dans le code et les tables.

**Comment by Elineau** [comment]
Nous n'ouvrons pas les samples 1 par 1 lors de l'étape du barcode et du fill in metadata. Cela serait trop long lors des inventaires à la réception.

De plus, certains éléments pertubateurs ne se voient QUE au moment du tamis et du scan : soupe microalgale et borax. 
Ouvrir le flacon ne suffit pas pour les voir.

Donc si pas possible de déménager ce champ on continue de faire du Edit metadata après coup.
